[package]
name = "sam-fuzzy"
version = "0.1.0"
edition = "2024"
license = "MIT"
authors = ["KR Shanto"]
description = "Blazing-fast terminal media explorer for SamOnline (DhakaFlix) FTP servers"
repository = "https://github.com/Shantodotdev/sam-fuzzy"

[dependencies]
ratatui = "0.29"
crossterm = "0.28"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
nucleo-matcher = "0.3"
open = "5.3"
arboard = "3.4"
unicode-width = "0.2"
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
rayon = "1.10"
flate2 = { version = "1.0", default-features = false, features = ["rust_backend"] }

[profile.test]
opt-level = 2

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true
